image:
  repository: milos2002/shop-operator
  tag: main
  pullPolicy: Always

replicaCount: 1

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

rbac:
  create: true

serviceAccount:
  create: true
  name: ""
