image:
  repository: milos2002/shophub
  tag: main
  pullPolicy: Always

replicaCount: 1

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: shophub-discord.local
      paths:
        - path: /
          pathType: Prefix

resources:
  limits:
    cpu: 250m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

config:
  httpPort: "8080"
  jwtSecret: "change-me-before-deploy"
  db:
    host: postgresql.shophub.svc.cluster.local
    port: "5432"
    name: shophub_db
    user: shophub_user
    password: "change-me-before-deploy"
  kubeconfig: ""

podAnnotations:
  discord.shophub.io/channel: "alerts"

serviceMonitor:
  enabled: true
  interval: 15s
  path: /metrics

rbac:
  create: false

serviceAccount:
  create: false
  name: shophub
